catalog/urls.py
from django.urls import path 

from . import views

urlpatterns = [
    path('',views.index , name = 'index'),
    path('books/',views.BookListView.as_view(), name = 'books'),
    path('authors/',views.AuthorListView.as_view(),name = 'authors'),
    path('book/<int:pk>/',views.BookDetailView.as_view(),name = 'book-detail'),
    path('author/<int:pk>',views.AuthorDetailView.as_view(),name = 'author-detail'),
    path('mybooks/', views.LoanedBooksByUserListView.as_view(), name='my-borrowed'),
]

catalog/models.py
from re import L
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

from datetime import date
import uuid

# Create your models here.
class Lang(models.Model):
    """Model representing the language"""

    lang = models.CharField(
        "Language" ,
        max_length = 5,
        default = 'Eng' 
        )

    def __str__(self):
        return self.lang


class Author(models.Model):
    """Model representing an author."""
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('Died', null=True, blank=True)

    class Meta:
        ordering = ['last_name', 'first_name']

    def get_absolute_url(self):
        """Returns the URL to access a particular author instance."""
        return reverse('author-detail', args=[str(self.id)])

    def __str__(self):
        """String for representing the Model object."""
        return f'{self.last_name}, {self.first_name}'

class Genre(models.Model):
    """The genre class"""
    genre = models.CharField(
        max_length = 10 ,
        help_text = 'Genere of the Book.' ,
        
        )

    
    def __str__(self):
        return self.genre


class Book(models.Model):
    """The book class"""

    title = models.CharField(max_length = 50 , help_text = 'Title of the book.' ,)
    isbn = models.CharField('ISBN',max_length = 13 , unique = True , help_text = 'A 13 characters length unique id.<a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>')
    author = models.ForeignKey(Author , on_delete = models.CASCADE , help_text = 'Author of the book.' )
    summary = models.TextField(max_length = 100 ,help_text = 'A brief summary of the book.')
    genre = models.ManyToManyField(Genre  , help_text = 'Genere of the book.' )
    copies  = models.IntegerField(default = 0 , help_text = 'No of copies Available.')
    lang = models.ForeignKey(Lang , help_text = 'Language of the book.' ,on_delete = models.SET_NULL , null = True)

    def __str__(self):
        return self.title
    def get_absolute_url(self):
        """Returns the URL to access a detail record for this book."""
        return reverse('book-detail', args=[str(self.id)])
    class Meta:
        ordering = ['title' ]


class BookInstance(models.Model):

    """BookInstances class"""

    id = models.UUIDField(
        primary_key = True , 
        default = uuid.uuid4,
        help_text='Unique ID for this particular book across whole library'
        )

    book = models.ForeignKey(
        Book , 
        on_delete = models.RESTRICT
        )

    imprint = models.CharField(
        max_length=200
        )

    due_back = models.DateField(
        null=True, 
        blank=True)

    LOAN_STATUS = (
        ('m', 'Maintenance'),
        ('o', 'On loan'),
        ('a', 'Available'),
        ('r', 'Reserved'),
    )

    status = models.CharField(
            max_length = 1 ,
            choices = LOAN_STATUS ,
            help_text = 'Status of the Instance.' ,
            
            )
    borrower = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)


    class Meta:
        ordering = ['due_back']

    def is_overdue(self):

        return bool(self.due_back and date.today() > self.due_back )

    def __str__(self):
        """String for representing the Model object."""
        return f'{self.id} ({self.book.title})'

catalog/views.py
from django.shortcuts import render
from django.views import generic
from .models import Book, Author, BookInstance, Genre
from  django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

@login_required
def index(request):
    """View function for home page of site."""

    # Generate counts of some of the main objects
    num_books = Book.objects.all().count()
    num_instances = BookInstance.objects.all().count()

    # Available books (status = 'a')
    num_instances_available = BookInstance.objects.filter(status__exact='a').count()

    # The 'all()' is implied by default.
    num_authors = Author.objects.count()

    num_visits = request.session.get('num_visits',0)
    request.session['num_visits'] = num_visits + 1

    context = {
        'num_books': num_books,
        'num_instances': num_instances,
        'num_instances_available': num_instances_available,
        'num_authors': num_authors,
        'num_visits' : num_visits
    }

    # Render the HTML template index.html with the data in the context variable
    return render(request, 'catalog/index.html', context=context)


class BookListView(LoginRequiredMixin,generic.ListView):
    model = Book
    context_object_name = 'book_list'   # your own name for the list as a template variable
    #queryset = Book.objects.filter(title__icontains='war')[:5] # Get 5 books containing the title war
    template_name = 'catalog/book_list.html'  # Specify your own template name/location
    paginate_by = 2

class AuthorListView(LoginRequiredMixin,generic.ListView):

    model = Author
    context_object_name = 'author_list'   # your own name for the list as a template variable
    #queryset = Book.objects.filter(title__icontains='war')[:5] # Get 5 books containing the title war
    template_name = 'catalog/author_list.html'  # Specify your own template name/location
    paginate_by = 2

class BookDetailView(LoginRequiredMixin,generic.DetailView):
    model = Book
    
    
class AuthorDetailView(LoginRequiredMixin,generic.DetailView):
    model = Author



class LoanedBooksByUserListView(LoginRequiredMixin,generic.ListView):
    """Generic class-based view listing books on loan to current user."""
    model = BookInstance
    template_name ='catalog/books_instances_by_user.html'
    paginate_by = 3

    def get_queryset(self):
        return BookInstance.objects.filter(borrower=self.request.user).order_by('due_back')

    

catalog/templates/catalog/author_detail.html
{% extends "catalog/base_generic.html" %}

{% block content %}
  <h1>Author: {{ author.first_name }},{{ author.last_name }}</h1>

        <p>{% if author.date_of_birth %} 
                {{author.date_of_birth}}
            {% else %}
                NA
            {% endif %}
            -
            {% if author.date_of_death %} 
                {{author.date_of_death}}
            {% else %}
                NA
            {% endif %}</p>

  <div style="margin-left:20px;margin-top:20px">
    <h4>Books :</h4>
    {% if author.book_set.all%}
        {% for book in author.book_set.all %}
            <h4><a href="{{ book.get_absolute_url }}">{{book.title}}</a></h4>
            <p>{{ book.summary }}</p>
     
        {% endfor %}
    {% else %}
        <p>No books in Database related to <a href="{{ author.get_absolute_url }}">{{author.first_name}},{{author.last_name}}</a>.</p>
    {% endif%}
  </div>
{% endblock %}

catalog/templates/catalog/author_list.html
{% extends "catalog/base_generic.html" %}

{% block content %}
  
  <h1>Author List</h1>
  {% if author_list %}
  <ul>
    {% for author in author_list %}
      <li>
        <a href="{{ author.get_absolute_url }}">{{ author.first_name}},{{author.last_name }}(
            {% if author.date_of_birth %} 
                {{author.date_of_birth}} 
            {% endif %}
            -
            {% if author.date_of_death %} 
                {{author.date_of_death}}
            {% endif %}
            )</a> 
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no Authors in the Database.</p>
  {% endif %}

  
{% endblock %}

catalog/templates/catalog/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% block title %}<title>Local Library</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <!-- Add additional CSS in static file -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-2">
      {% block sidebar %}
        <ul class="sidebar-nav">
          <li><a href="{% url 'index' %}">Home</a></li>
          <li><a href="{% url 'books' %}">All books</a></li>
          <li><a href="{% url 'authors' %}">All authors</a></li>
        </ul>
     {% endblock %}

     <ul class="sidebar-nav">
      {% if user.is_authenticated %}
      <li>User: {{ user.get_username }}</li>
   
      <li><a href="{% url 'my-borrowed' %}">My Borrowed</a></li>
   
      <li><a href="{% url 'auth:logout'%}?next={{request.path}}">Logout</a></li>
      {% else %}
      <li><a href="{% url 'auth:login'%}?next={{request.path}}">Login</a></li>
      {% endif %}
    </ul>
      </div>
      <div class="col-sm-10 ">
        {% block content %}
        {% endblock %} 
        
        {% block pagination %}
          {% if is_paginated %}
            <div class="pagination">
                <span class="page-links">
                    {% if page_obj.has_previous %}
                        <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
                    {% endif %}
                    <span class="page-current">
                        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                    </span>
                    {% if page_obj.has_next %}
                        <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
                    {% endif %}
                </span>
            </div>
            {% endif %}
        {% endblock %}
     
    </div>
    </div>
  </div>
</body>
</html>

catalog/templates/catalog/book_detail.html
{% extends "catalog/base_generic.html" %}

{% block content %}
  <h1>Title: {{ book.title }}</h1>

  <p><strong>Author:</strong> <a href="{{ book.author.get_absolute_url }}">{{ book.author }}</a></p> <!-- author detail link not yet defined -->
  <p><strong>Summary:</strong> {{ book.summary }}</p>
  <p><strong>ISBN:</strong> {{ book.isbn }}</p>
  <p><strong>Language:</strong> {{ book.language }}</p>
  <p><strong>Genre:</strong> {{ book.genre.all|join:", " }}</p>

  <div style="margin-left:20px;margin-top:20px">
    <h4>Copies :</h4>

    {% for copy in book.bookinstance_set.all %}
      
      
      <p class="{% if copy.status == 'o' %}text-success{% elif copy.status == 'm' %}text-danger{% else %}text-warning{% endif %}" >
         {{ copy.status }}
      </p >
      {% if copy.status != 'a' %}
        <p><strong>Due to be returned:</strong> {{ copy.due_back }}</p>
      {% endif %}
      <p><strong>Imprint:</strong> {{ copy.imprint }}</p>
      <p class="text-muted"><strong>Id:</strong> {{ copy.id }}</p>
     
    {% endfor %}

  </div>
{% endblock %}

catalog/templates/catalog/book_list.html
{% extends "catalog/base_generic.html" %}

{% block content %}
  {% if user.is_authenticated %}
  <h1>Book List</h1>
  {% if book_list %}
  <ul>
    {% for book in book_list %}
      <li>
        <a href="{{ book.get_absolute_url }}">{{ book.title }}</a> ({{book.author}})
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no books in the library.</p>
  {% endif %}

  {% else %}
  <strong><p>Please login to view this Page</p></strong>
  {% endif %}
{% endblock %}

catalog/templates/catalog/books_instances_by_user.html
{% extends "catalog/base_generic.html" %}

{% block content %}
    <h1>Borrowed books</h1>

    {% if bookinstance_list %}
    <ul>

      {% for bookinst in bookinstance_list %}
      <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'book-detail' bookinst.book.pk %}">{{bookinst.book.title}}</a> ({{ bookinst.due_back }})
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>There are no books borrowed.</p>
    {% endif %}
{% endblock %}

catalog/templates/catalog/index.html
{% extends "catalog/base_generic.html" %}

{% block content %}
{% if user.is_authenticated%}
  <h1>Local Library Home</h1>
  <p>Welcome to LocalLibrary, a website developed by <em>Siddhartha Reddy Machi </em></p>
  <h2>Dynamic content</h2>
  <p>The library has the following record counts:</p>
  <ul>
    <li><strong>Books:</strong> {{ num_books }}</li>
    <li><strong>Copies:</strong> {{ num_instances }}</li>
    <li><strong>Copies available:</strong> {{ num_instances_available }}</li>
    <li><strong>Authors:</strong> {{ num_authors }}</li>
  </ul>
  <p>You have visited this page {{ num_visits }} time{{ num_visits|pluralize }}.</p>
{% else %}
  <strong><p>Please login to view this Page</p></strong>
{% endif %}
{% endblock %}